# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag
